#!/bin/bash

PYFLG=1

CWD=`pwd`
SUMMARY=$CWD/summary.txt
THRESH=".00001"

echo "This is a summary of values obtained from the master version and current version" > $SUMMARY

if [ "$#" -eq 0 ]; then
  NAESMDEXE=nexmd.exe
  echo "Using `which ${NAESMDEXE}`"
  echo "Using `which ${NAESMDEXE}`" >> $SUMMARY
elif [ "$#" -eq 1 ]; then
  if [ $1 == "clean" ]; then
    #clean script
    rm -r runtests
	  rm REFvec
	  rm RUNvec
	  rm REFvecPY
	  rm RUNvecPY
	  echo "Clean Files" 
	  exit 0
  fi
  NAESMDEXE=$1
  echo "Using $NAESMDEXE"
  echo "Using $NAESMDEXE" >> $SUMMARY
else
  echo "Only input option is full msqceonesmd.exe path."
fi

mkdir -p runtests

if [ $PYFLG -eq 1 ] ; then
 echo 'yes python'
else
 echo 'no python'
fi

CompVecs ()
{ # This function compares the files REFvec and RUNvec, returns match if they match, or prints them side by side
if cmp --silent RUNvec REFvec ; then
 # echo "files are the same"
 echo "Match"
else
 # echo "files are differnt"
 echo "Discrepancy"
 echo '< Reference | Run > '
 diff REFvec RUNvec >> $SUMMARY
 #echo "Reference" >> $SUMMARY
 #cat REFvec >> $SUMMARY
 #echo "Current" >> $SUMMARY
 #cat RUNvec >> $SUMMARY
fi
} 

CompPy ()
{ # This function compares the files REFvec and RUNvec, returns match if they match, or prints them side by side
cat RUNvec | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvecPY
cat REFvec | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvecPY
${CWD}/rms.py REFvecPY RUNvecPY $THRESH
if [ $? -eq 1 ] ; then
 # echo "files are the same"
 echo "Within Tolerance"
else
 # echo "files are differnt"
 echo "Discrepancy"
 CompVecs
 # echo '< Reference | Run > '
 # diff REFvec RUNvec >> $SUMMARY
 # echo "Reference" >> $SUMMARY
 # cat REFvec >> $SUMMARY
 # echo "Current" >> $SUMMARY
 # cat RUNvec >> $SUMMARY
fi
echo -n "RMS Error: "
${CWD}/rms.py REFvecPY RUNvecPY
# echo "" >> $SUMMARY
# cat RUNvec >> $SUMMARY
# echo "" >> $SUMMARY
# cat REFvec >> $SUMMARY
# echo "" >> $SUMMARY
} 

Comp ()
{
if [ $PYFLG -eq 1 ] ; then
  CompPy >> $SUMMARY
else
  CompVecs >> $SUMMARY
fi
}

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="singlepoint/test4/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD

CURRSTR="Total energy of the ground state (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 1 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
grep -A 1 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Total energies of excited states (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 | sed "/$CURRSTR/d" > RUNvec
grep -A 3 "$CURRSTR" ${RUN}/output | tail -n 3 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 | sed "/$CURRSTR/d" > RUNvec
grep -A 3 "$CURRSTR" ${RUN}/output | tail -n 3 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18- > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18- > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="singlepoint/test4/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD

CURRSTR="Total energy of the ground state (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 1 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
grep -A 1 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Total energies of excited states (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 | sed "/$CURRSTR/d" > RUNvec
grep -A 3 "$CURRSTR" ${RUN}/output | tail -n 3 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output | tail -n 2 | sed "/$CURRSTR/d" > RUNvec
grep -A 2 "$CURRSTR" ${RUN}/output | tail -n 2 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18- > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18- > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="singlepoint/test12/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD

CURRSTR="Total energy of the ground state (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 1 "$CURRSTR" ${REF}/output | tail -n 1 > REFvec
grep -A 1 "$CURRSTR" ${REF}/output | tail -n 1 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Total energies of excited states (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 > REFvec
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output | tail -n 1 | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output | tail -n 1 | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 | sed "/$CURRSTR/d" > RUNvec
grep -A 3 "$CURRSTR" ${RUN}/output | tail -n 3 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 | sed "/$CURRSTR/d" > RUNvec
grep -A 3 "$CURRSTR" ${RUN}/output | tail -n 3 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18- > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18- > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="singlepoint/test12/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD

CURRSTR="Total energy of the ground state (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 1 "$CURRSTR" ${REF}/output | tail -n 1 > REFvec
grep -A 1 "$CURRSTR" ${REF}/output | tail -n 1 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Total energies of excited states (eV,AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 > REFvec
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output | tail -n 1 | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output | tail -n 1 | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output | tail -n 3 | sed "/$CURRSTR/d" > RUNvec
grep -A 3 "$CURRSTR" ${RUN}/output | tail -n 3 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output | tail -n 2 | sed "/$CURRSTR/d" > RUNvec
grep -A 2 "$CURRSTR" ${RUN}/output | tail -n 2 | sed "/$CURRSTR/d" > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18- > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18- > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18- > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ", Frequencies: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c6-18 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c6-18 > REFvec
Comp

echo -n $CURRSTR >> $SUMMARY
echo -n ", Dipole: " >> $SUMMARY
grep -A 4 "$CURRSTR" ${RUN}/output | tail -n 3 | cut -c18-66 > RUNvec
grep -A 4 "$CURRSTR" ${REF}/output | tail -n 3 | cut -c18-66 > REFvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="geomopt/test1/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

CURRSTR="Final Structure"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 12 "$CURRSTR" ${REF}/output.tac | tail -n 12 > REFvec
grep -A 12 "$CURRSTR" ${RUN}/output.tac | tail -n 12 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

#CURRSTR="QMMM: Occupied MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY
#
#CURRSTR="QMMM: Virtual MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="geomopt/test1/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

CURRSTR="Final Structure"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 7 "$CURRSTR" ${REF}/output.tac | tail -n 7 > REFvec
grep -A 7 "$CURRSTR" ${RUN}/output.tac | tail -n 7 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

#CURRSTR="QMMM: Occupied MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY
#
#CURRSTR="QMMM: Virtual MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 2 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 2 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="geomopt/test2/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

CURRSTR="Final Structure"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 12 "$CURRSTR" ${REF}/output.tac | tail -n 12 > REFvec
grep -A 12 "$CURRSTR" ${RUN}/output.tac | tail -n 12 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

#CURRSTR="QMMM: Occupied MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY
#
#CURRSTR="QMMM: Virtual MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="geomopt/test2/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

CURRSTR="Final Structure"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 7 "$CURRSTR" ${REF}/output.tac | tail -n 7 > REFvec
grep -A 7 "$CURRSTR" ${RUN}/output.tac | tail -n 7 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

#CURRSTR="QMMM: Occupied MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY
#
#CURRSTR="QMMM: Virtual MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 2 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 2 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="geomopt/test3/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

CURRSTR="Final Structure"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 12 "$CURRSTR" ${REF}/output.tac | tail -n 12 > REFvec
grep -A 12 "$CURRSTR" ${RUN}/output.tac | tail -n 12 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

#CURRSTR="QMMM: Occupied MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY
#
#CURRSTR="QMMM: Virtual MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 13 "$CURRSTR" $RUN/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 13 "$CURRSTR" $REF/output | tail -n 12 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="geomopt/test3/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

CURRSTR="Final Structure"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 7 "$CURRSTR" ${REF}/output.tac | tail -n 7 > REFvec
grep -A 7 "$CURRSTR" ${RUN}/output.tac | tail -n 7 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

#CURRSTR="QMMM: Occupied MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 3 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 3 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY
#
#CURRSTR="QMMM: Virtual MO Energies (eV)"
#echo -n $CURRSTR >> $SUMMARY
#echo -n ": " >> $SUMMARY
#grep -A 2 "$CURRSTR" ${REF}/output | sed "/$CURRSTR/d" > REFvec
#grep -A 2 "$CURRSTR" ${RUN}/output | sed "/$CURRSTR/d" > RUNvec
#CompVecs >> $SUMMARY
#
#echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms excited state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Excited State Forces on QM atoms from SCF calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
if [ $PYFLG -eq 1 ] ; then
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | tr '\n' ' ' | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  ./rms.py RUNvec REFvec >> $SUMMARY
else
  grep -A 8 "$CURRSTR" $RUN/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > RUNvec
  grep -A 8 "$CURRSTR" $REF/output | tail -n 7 | cut -c18- | sed -e 's/ *$//' | sed -e 's/  */ /g' | sed -e 's/^ //' > REFvec
  CompVecs >> $SUMMARY
fi

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (Debye)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) and Total Molecular Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Unrelaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="Frequencies (eV) Relaxed Difference Dipole Moments (AU)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 4 "$CURRSTR" ${REF}/output.tac | tail -n 3 > REFvec
grep -A 4 "$CURRSTR" ${RUN}/output.tac | tail -n 3 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test5/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 12 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 12 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test5/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test6/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 12 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 12 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test6/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test7/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 2 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 2 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test7/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test8/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 12 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 12 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test8/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test9/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 12 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 12 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test9/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test10/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 12 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 12 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test10/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test11/benzene"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 12 "time =       ${i}" ${REF}/coords.xyz | tail -n 12 | cut -c5- > REFvec
grep -A 12 "time =       ${i}" ${RUN}/coords.xyz | tail -n 12 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 13 "time =       ${i}" ${REF}/velocity.out | tail -n 12 > REFvec
grep -A 13 "time =       ${i}" ${RUN}/velocity.out | tail -n 12 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 13 "$CURRSTR" ${RUN}/output | tail -n 12 | cut -c18-  > RUNvec
grep -A 13 "$CURRSTR" ${REF}/output | tail -n 12 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp

echo "" >> $SUMMARY
echo "-----------------------------------------------------------------------" >> $SUMMARY
CURR="bodynamics/test11/nitromethane"
echo "Check calculation $CURR" >> $SUMMARY
echo "" >> $SUMMARY

REF=$CWD/../tests/$CURR
RUN=$CWD/runtests/$CURR
mkdir -p $RUN
cd $RUN
cp ${REF}/input.ceon ${RUN} 
${NAESMDEXE} > output
cd $CWD
tac $REF/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $REF/output.tac
tac $RUN/output | sed '/^QMMM: SCF Convergence Information/q' | tac > $RUN/output.tac

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Coordinates for time ${i}:" >> $SUMMARY
grep -A 7 "time =       ${i}" ${REF}/coords.xyz | tail -n 7 | cut -c5- > REFvec
grep -A 7 "time =       ${i}" ${RUN}/coords.xyz | tail -n 7 | cut -c5- > RUNvec
Comp
done

echo "" >> $SUMMARY

for i in 0.1000 0.2000 0.3000 0.4000 0.5000 0.6000 0.7000 0.8000 0.9000 1.0000
do
echo -n "Velocities for time $i:" >> $SUMMARY
grep -A 8 "time =       ${i}" ${REF}/velocity.out | tail -n 7 > REFvec
grep -A 8 "time =       ${i}" ${RUN}/velocity.out | tail -n 7 > RUNvec
Comp
done

echo "" >> $SUMMARY

CURRSTR="QMMM:             Total energy ="
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep "$CURRSTR" ${REF}/output.tac | cut -c33-52 > REFvec
grep "$CURRSTR" ${RUN}/output.tac | cut -c33-52 > RUNvec
CompVecs >> $SUMMARY

echo "" >> $SUMMARY

CURRSTR="QMMM: Occupied MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 3 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 3 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="QMMM: Virtual MO Energies (eV)"
echo -n $CURRSTR >> $SUMMARY
echo -n ": " >> $SUMMARY
grep -A 2 "$CURRSTR" ${REF}/output.tac | sed "/$CURRSTR/d" > REFvec
grep -A 2 "$CURRSTR" ${RUN}/output.tac | sed "/$CURRSTR/d" > RUNvec
Comp

echo "" >> $SUMMARY

CURRSTR="Forces on QM atoms ground state calculation"
echo -n $CURRSTR >> $SUMMARY
echo -n " RMSD: " >> $SUMMARY
grep -A 8 "$CURRSTR" ${RUN}/output | tail -n 7 | cut -c18-  > RUNvec
grep -A 8 "$CURRSTR" ${REF}/output | tail -n 7 | cut -c18-  > REFvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature (T) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c21-40 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c21-40 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Temperature Difference (T-T0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c42-59 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c42-59 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy (U) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c59-79 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c59-79 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Potential Energy Difference (U-U0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c80-97 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c80-97 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy (E) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c97-116 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c97-116 > RUNvec
Comp

echo "" >> $SUMMARY

echo -n "Total Energy Difference (E-E0) from energy-ev.out:" >> $SUMMARY
tail -n 11 ${REF}/energy-ev.out | cut -c116-134 > REFvec
tail -n 11 ${RUN}/energy-ev.out | cut -c116-134 > RUNvec
Comp
